export type JobLocationOption = {
  value: string;
  label: string;
};

const viLocations: JobLocationOption[] = [
  { value: 'An Giang', label: 'An Giang' },
  { value: 'Bà Rịa - Vũng Tàu', label: 'Bà Rịa - Vũng Tàu' },
  { value: 'Bắc Giang', label: 'Bắc Giang' },
  { value: 'Bắc Kạn', label: 'Bắc Kạn' },
  { value: 'Bạc Liêu', label: 'Bạc Liêu' },
  { value: 'Bắc Ninh', label: 'Bắc Ninh' },
  { value: 'Bến Tre', label: 'Bến Tre' },
  { value: 'Bình Định', label: 'Bình Định' },
  { value: 'Bình Dương', label: 'Bình Dương' },
  { value: 'Bình Phước', label: 'Bình Phước' },
  { value: 'Bình Thuận', label: 'Bình Thuận' },
  { value: 'Cà Mau', label: 'Cà Mau' },
  { value: 'Cần Thơ', label: 'Cần Thơ' },
  { value: 'Cao Bằng', label: 'Cao Bằng' },
  { value: 'Đà Nẵng', label: 'Đà Nẵng' },
  { value: 'Đắk Lắk', label: 'Đắk Lắk' },
  { value: 'Đắk Nông', label: 'Đắk Nông' },
  { value: 'Điện Biên', label: 'Điện Biên' },
  { value: 'Đồng Nai', label: 'Đồng Nai' },
  { value: 'Đồng Tháp', label: 'Đồng Tháp' },
  { value: 'Gia Lai', label: 'Gia Lai' },
  { value: 'Hà Giang', label: 'Hà Giang' },
  { value: 'Hà Nam', label: 'Hà Nam' },
  { value: 'Hà Nội', label: 'Hà Nội' },
  { value: 'Hà Tĩnh', label: 'Hà Tĩnh' },
  { value: 'Hải Dương', label: 'Hải Dương' },
  { value: 'Hải Phòng', label: 'Hải Phòng' },
  { value: 'Hậu Giang', label: 'Hậu Giang' },
  { value: 'Hòa Bình', label: 'Hòa Bình' },
  { value: 'Hưng Yên', label: 'Hưng Yên' },
  { value: 'Khánh Hòa', label: 'Khánh Hòa' },
  { value: 'Kiên Giang', label: 'Kiên Giang' },
  { value: 'Kon Tum', label: 'Kon Tum' },
  { value: 'Lai Châu', label: 'Lai Châu' },
  { value: 'Lâm Đồng', label: 'Lâm Đồng' },
  { value: 'Lạng Sơn', label: 'Lạng Sơn' },
  { value: 'Lào Cai', label: 'Lào Cai' },
  { value: 'Long An', label: 'Long An' },
  { value: 'Nam Định', label: 'Nam Định' },
  { value: 'Nghệ An', label: 'Nghệ An' },
  { value: 'Ninh Bình', label: 'Ninh Bình' },
  { value: 'Ninh Thuận', label: 'Ninh Thuận' },
  { value: 'Phú Thọ', label: 'Phú Thọ' },
  { value: 'Phú Yên', label: 'Phú Yên' },
  { value: 'Quảng Bình', label: 'Quảng Bình' },
  { value: 'Quảng Nam', label: 'Quảng Nam' },
  { value: 'Quảng Ngãi', label: 'Quảng Ngãi' },
  { value: 'Quảng Ninh', label: 'Quảng Ninh' },
  { value: 'Quảng Trị', label: 'Quảng Trị' },
  { value: 'Sóc Trăng', label: 'Sóc Trăng' },
  { value: 'Sơn La', label: 'Sơn La' },
  { value: 'Tây Ninh', label: 'Tây Ninh' },
  { value: 'Thái Bình', label: 'Thái Bình' },
  { value: 'Thái Nguyên', label: 'Thái Nguyên' },
  { value: 'Thanh Hóa', label: 'Thanh Hóa' },
  { value: 'Thừa Thiên Huế', label: 'Thừa Thiên Huế' },
  { value: 'Tiền Giang', label: 'Tiền Giang' },
  { value: 'TP. Hồ Chí Minh', label: 'TP. Hồ Chí Minh' },
  { value: 'Trà Vinh', label: 'Trà Vinh' },
  { value: 'Tuyên Quang', label: 'Tuyên Quang' },
  { value: 'Vĩnh Long', label: 'Vĩnh Long' },
  { value: 'Vĩnh Phúc', label: 'Vĩnh Phúc' },
  { value: 'Yên Bái', label: 'Yên Bái' },
  { value: 'Làm từ xa', label: 'Làm từ xa' },
];

const enLocations: JobLocationOption[] = [
  { value: 'An Giang', label: 'An Giang' },
  { value: 'Ba Ria - Vung Tau', label: 'Ba Ria - Vung Tau' },
  { value: 'Bac Giang', label: 'Bac Giang' },
  { value: 'Bac Kan', label: 'Bac Kan' },
  { value: 'Bac Lieu', label: 'Bac Lieu' },
  { value: 'Bac Ninh', label: 'Bac Ninh' },
  { value: 'Ben Tre', label: 'Ben Tre' },
  { value: 'Binh Dinh', label: 'Binh Dinh' },
  { value: 'Binh Duong', label: 'Binh Duong' },
  { value: 'Binh Phuoc', label: 'Binh Phuoc' },
  { value: 'Binh Thuan', label: 'Binh Thuan' },
  { value: 'Ca Mau', label: 'Ca Mau' },
  { value: 'Can Tho', label: 'Can Tho' },
  { value: 'Cao Bang', label: 'Cao Bang' },
  { value: 'Da Nang', label: 'Da Nang' },
  { value: 'Dak Lak', label: 'Dak Lak' },
  { value: 'Dak Nong', label: 'Dak Nong' },
  { value: 'Dien Bien', label: 'Dien Bien' },
  { value: 'Dong Nai', label: 'Dong Nai' },
  { value: 'Dong Thap', label: 'Dong Thap' },
  { value: 'Gia Lai', label: 'Gia Lai' },
  { value: 'Ha Giang', label: 'Ha Giang' },
  { value: 'Ha Nam', label: 'Ha Nam' },
  { value: 'Hanoi', label: 'Hanoi' },
  { value: 'Ha Tinh', label: 'Ha Tinh' },
  { value: 'Hai Duong', label: 'Hai Duong' },
  { value: 'Hai Phong', label: 'Hai Phong' },
  { value: 'Hau Giang', label: 'Hau Giang' },
  { value: 'Hoa Binh', label: 'Hoa Binh' },
  { value: 'Hung Yen', label: 'Hung Yen' },
  { value: 'Khanh Hoa', label: 'Khanh Hoa' },
  { value: 'Kien Giang', label: 'Kien Giang' },
  { value: 'Kon Tum', label: 'Kon Tum' },
  { value: 'Lai Chau', label: 'Lai Chau' },
  { value: 'Lam Dong', label: 'Lam Dong' },
  { value: 'Lang Son', label: 'Lang Son' },
  { value: 'Lao Cai', label: 'Lao Cai' },
  { value: 'Long An', label: 'Long An' },
  { value: 'Nam Dinh', label: 'Nam Dinh' },
  { value: 'Nghe An', label: 'Nghe An' },
  { value: 'Ninh Binh', label: 'Ninh Binh' },
  { value: 'Ninh Thuan', label: 'Ninh Thuan' },
  { value: 'Phu Tho', label: 'Phu Tho' },
  { value: 'Phu Yen', label: 'Phu Yen' },
  { value: 'Quang Binh', label: 'Quang Binh' },
  { value: 'Quang Nam', label: 'Quang Nam' },
  { value: 'Quang Ngai', label: 'Quang Ngai' },
  { value: 'Quang Ninh', label: 'Quang Ninh' },
  { value: 'Quang Tri', label: 'Quang Tri' },
  { value: 'Soc Trang', label: 'Soc Trang' },
  { value: 'Son La', label: 'Son La' },
  { value: 'Tay Ninh', label: 'Tay Ninh' },
  { value: 'Thai Binh', label: 'Thai Binh' },
  { value: 'Thai Nguyen', label: 'Thai Nguyen' },
  { value: 'Thanh Hoa', label: 'Thanh Hoa' },
  { value: 'Thua Thien Hue', label: 'Thua Thien Hue' },
  { value: 'Tien Giang', label: 'Tien Giang' },
  { value: 'Ho Chi Minh City', label: 'Ho Chi Minh City' },
  { value: 'Tra Vinh', label: 'Tra Vinh' },
  { value: 'Tuyen Quang', label: 'Tuyen Quang' },
  { value: 'Vinh Long', label: 'Vinh Long' },
  { value: 'Vinh Phuc', label: 'Vinh Phuc' },
  { value: 'Yen Bai', label: 'Yen Bai' },
  { value: 'Remote', label: 'Remote' },
];

/** Map EN filter values to VI job data values for cross-locale filtering. */
const enToViLocationValue: Record<string, string> = {
  'Ba Ria - Vung Tau': 'Bà Rịa - Vũng Tàu',
  'Bac Giang': 'Bắc Giang',
  'Bac Kan': 'Bắc Kạn',
  'Bac Lieu': 'Bạc Liêu',
  'Bac Ninh': 'Bắc Ninh',
  'Ben Tre': 'Bến Tre',
  'Binh Dinh': 'Bình Định',
  'Binh Duong': 'Bình Dương',
  'Binh Phuoc': 'Bình Phước',
  'Binh Thuan': 'Bình Thuận',
  'Ca Mau': 'Cà Mau',
  'Can Tho': 'Cần Thơ',
  'Cao Bang': 'Cao Bằng',
  'Da Nang': 'Đà Nẵng',
  'Dak Lak': 'Đắk Lắk',
  'Dak Nong': 'Đắk Nông',
  'Dien Bien': 'Điện Biên',
  'Dong Nai': 'Đồng Nai',
  'Dong Thap': 'Đồng Tháp',
  'Ha Giang': 'Hà Giang',
  'Ha Nam': 'Hà Nam',
  Hanoi: 'Hà Nội',
  'Ha Tinh': 'Hà Tĩnh',
  'Hai Duong': 'Hải Dương',
  'Hai Phong': 'Hải Phòng',
  'Hau Giang': 'Hậu Giang',
  'Hoa Binh': 'Hòa Bình',
  'Hung Yen': 'Hưng Yên',
  'Khanh Hoa': 'Khánh Hòa',
  'Kien Giang': 'Kiên Giang',
  'Kon Tum': 'Kon Tum',
  'Lai Chau': 'Lai Châu',
  'Lam Dong': 'Lâm Đồng',
  'Lang Son': 'Lạng Sơn',
  'Lao Cai': 'Lào Cai',
  'Long An': 'Long An',
  'Nam Dinh': 'Nam Định',
  'Nghe An': 'Nghệ An',
  'Ninh Binh': 'Ninh Bình',
  'Ninh Thuan': 'Ninh Thuận',
  'Phu Tho': 'Phú Thọ',
  'Phu Yen': 'Phú Yên',
  'Quang Binh': 'Quảng Bình',
  'Quang Nam': 'Quảng Nam',
  'Quang Ngai': 'Quảng Ngãi',
  'Quang Ninh': 'Quảng Ninh',
  'Quang Tri': 'Quảng Trị',
  'Soc Trang': 'Sóc Trăng',
  'Son La': 'Sơn La',
  'Tay Ninh': 'Tây Ninh',
  'Thai Binh': 'Thái Bình',
  'Thai Nguyen': 'Thái Nguyên',
  'Thanh Hoa': 'Thanh Hóa',
  'Thua Thien Hue': 'Thừa Thiên Huế',
  'Tien Giang': 'Tiền Giang',
  'Ho Chi Minh City': 'TP. Hồ Chí Minh',
  'Tra Vinh': 'Trà Vinh',
  'Tuyen Quang': 'Tuyên Quang',
  'Vinh Long': 'Vĩnh Long',
  'Vinh Phuc': 'Vĩnh Phúc',
  'Yen Bai': 'Yên Bái',
  Remote: 'Làm từ xa',
};

export function getJobSearchLocations(locale: 'vi' | 'en'): JobLocationOption[] {
  return locale === 'en' ? enLocations : viLocations;
}

export function resolveLocationFilterValues(locations: string[], locale: 'vi' | 'en'): string[] {
  if (locale === 'vi') {
    return locations;
  }
  return locations.map((location) => enToViLocationValue[location] ?? location);
}

export function formatSelectedLocations(
  selected: string[],
  locations: JobLocationOption[],
  labels: { placeholder: string; selectedCount: (count: number) => string },
): string {
  if (selected.length === 0) {
    return labels.placeholder;
  }
  if (selected.length === 1) {
    return locations.find((option) => option.value === selected[0])?.label ?? selected[0];
  }
  return labels.selectedCount(selected.length);
}
